<script module>
	import { defineMeta } from '@storybook/addon-svelte-csf';
	import CardFilters from '$lib/components/CardFilters.svelte';
	import { SearchFilter } from '$lib/SearchFilter.svelte';

	const { Story } = defineMeta({
		component: CardFilters,
		args: {
			search: new SearchFilter(),
			sets: [
				{ id: 385, idText: 'spdeck13', name: 'コロコロ・スペシャル デッキ13' },
				{ id: 384, idText: 'dm26rp1', name: 'DM26-RP1 逆札篇 第1弾 逆転神VS切札竜' },
				{ id: 7, idText: 'dm05', name: 'DM-05 漂流大陸の末裔(リターン・オブ・ザ・サバイバー)' },
				{ id: 6, idText: 'dm04', name: 'DM-04 闇騎士団の逆襲(チャレンジ・オブ・ブラックシャドウ)' },
				{ id: 5, idText: 'sp', name: '特別商品限定カード' },
				{ id: 4, idText: 'dm03', name: 'DM-03 超戦士襲撃(マスター・オブ・デストラクション)' },
				{ id: 3, idText: 'promoy1', name: 'プロモ限定カード 1期' },
				{ id: 2, idText: 'dm02', name: 'DM-02 進化獣降臨(マスター・オブ・エボリューション)' },
				{ id: 1, idText: 'dm01', name: 'DM-01' }
			],
			species: [
				'???',
				'2016カレンダー',
				'ACE',
				'S級侵略者',
				'アーク・セラフィム',
				'アークセラフィム',
				'アースイーター',
				'アース・ドラゴン',
				'アーマード・アーツ',
				'アーマード・アポロニア・ドラゴン',
				'アーマード・ファイアー・バード',
				'グランセクト・ワード',
				'グランド・デビル',
				'グリーン・コマンド・ドラゴン',
				'クリエイター',
				'クリスタル・コマンド・ドラゴン',
				'ヒューマノイド爆',
				'ヒューマノイド邪',
				'ファイアー・バード',
				'ファイアー・バードの集い',
				'ファイアー・バード炎',
				'マジック・マーフォーク',
				'マジック・リキッド・ピープル',
				'マシン・イーター',
				'マシン・イーター・ワード',
				'マスター・ＤＧ',
				'マスター・イニシャルズ',
				'マスター・イニシャルズX',
				'マスターズ・レガシー',
				'∞マスター・ドラゴン',
				'マスター・ドラゴン',
				'リキシ・コマンド',
				'リキシ・コマンド・ドラゴン',
				'リキッド・ピープル',
				'リキッド・ピープル閃',
				'リビング・デッド',
				'ルージュアビス',
				'ルナーズ・サンガイザー',
				'ルナティック・エンペラー',
				'ルリグ',
				'レインボー・コマンド・ドラゴン',
				'レインボー・ドラゴン',
				'ワールド・バード',
				'ワイルド・ベジーズ',
				'ワンダー・トリック',
				'ワンダフォース',
				'不死樹王国',
				'侵略者',
				'侵略者ZERO',
				'暴拳王国',
				'月光王国',
				'猫',
				'禁断',
				'禁断ソニック・コマンド',
				'美孔麗王国',
				'裁きの紋章',
				'裁きの紋章Z',
				'超化獣',
				'革命軍',
				'鬼レクスターズ',
				'鬼札王国',
				'魔導具'
			],
			rarities: [
				{ code: 'NONE', order: 0, name: 'レアリティなし' },
				{ code: 'C', order: 1, name: 'C' },
				{ code: 'U', order: 2, name: 'U' },
				{ code: 'R', order: 3, name: 'R' },
				{ code: 'VR', order: 4, name: 'VR' },
				{ code: 'SR', order: 5, name: 'SR' },
				{ code: 'VIC', order: 6, name: 'VIC' },
				{ code: 'WVC', order: 7, name: 'WVC' },
				{ code: 'LEG', order: 8, name: 'LEG' },
				{ code: 'KDL', order: 9, name: 'KDL' },
				{ code: 'FFL', order: 10, name: 'FFL' },
				{ code: 'MAS', order: 11, name: 'MAS' },
				{ code: 'DG', order: 12, name: 'DG' },
				{ code: 'MDG', order: 13, name: 'MDG' },
				{ code: 'MDS', order: 14, name: 'MDS' },
				{ code: 'MHZ', order: 15, name: 'MHZ' },
				{ code: 'MSS', order: 16, name: 'MSS' },
				{ code: 'MSZ', order: 17, name: 'MSZ' },
				{ code: 'KGM', order: 18, name: 'KGM' },
				{ code: 'KGR', order: 19, name: 'KGR' },
				{ code: 'OR', order: 20, name: 'OR' },
				{ code: 'DSR', order: 22, name: 'DSR' },
				{ code: 'DMR', order: 23, name: 'DMR' },
				{ code: 'SPR', order: 24, name: 'SPR' }
			]
		}
	});
</script>

<Story name="Filters" />
