services:
  server:
    image: ghcr.io/dm-collection/server:latest
    ports:
      - "8080:8080"
    environment:
      DMCOLLECTION_IMAGE_STORAGE_PATH: /images
    volumes:
      - type: bind
        source: ./db-data
        target: /data
      - type: bind
        source: ./dmcollection-images
        target: /images
