services:
  server:
    image: ghcr.io/dm-collection/server:latest
    ports:
      - "8080:8080"
    environment:
      DMCOLLECTION_IMAGE_STORAGE_PATH: /images
    volumes:
      - type: bind
        source: ./db-data
        target: /home/nonroot/data
      - type: bind
        source: ./dmcollection-images
        target: /images

  imagor:
    image: shumc/imagor:latest
    ports:
      - "8000:8000"
    environment:
      FILE_LOADER_BASE_DIR: /images
      IMAGOR_UNSAFE: "1"
    volumes:
      - type: bind
        source: ./dmcollection-images
        target: /images
        read_only: true
