spring:
  config:
    import: optional:configtree:/run/secrets/
  application:
    name: Server
  datasource:
    url: jdbc:h2:file:./data/db;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: ${dmcollection_db_user:dev_user}
    password: ${dmcollection_db_password:devpw}
  h2:
    console:
      enabled: false
      path: /h2-console
  liquibase.change-log: classpath:db/changelog/db.changelog-master.yml
dmcollection:
  image-storage-path: ${dmcollection_image_storage_path:${user.home}/dmcollection-images}
  card-page:
    default-size: 40
    max-size: 100
  registration-code: ${dmcollection_registration_code:}
  remember-me-key: ${dmcollection_remember_me_key:devkey}
server:
  servlet:
    session:
      cookie:
        same-site: lax
        secure: true
        http-only: true
        max-age: 86400
