package net.dmcollection.model.card;

public enum RarityCode {
  NONE, // no rarity
  C, // COMMON
  U, // UNCOMMON
  R, // RARE
  VR, // VERY_RARE
  SR, // SUPER_RARE
  VIC, // VICTORY_RARE
  WVC, // DOUBLE_VICTORY
  LEG, // LEGEND_CARD
  KDL, // FORBIDDEN_LEGEND_CARD
  FFL, // FINAL_FORBIDDEN_LEGEND_CARD
  MAS, // MASTER_CARD
  DG, // DG_RARE
  MDG, // MASTER_DRAGON_CARD
  MDS, // MASTER_DOLSZAC_CARD
  MHZ, // MASTER_HAZARD_CARD
  MSS, // MASTER_SPECIAL_MOVE_CARD
  MSZ, // MASTER_Z_CARD
  KGM, // KING_MASTER_CARD
  KGR, // KING_RARE_CARD
  OR, // OVER_RARE
  SSR, // SPECIAL_SUPER_RARE
  DSR, // DAI_SENSEI_RARE
  DMR, // DREAM_RARE
  SPR; // HEROINE RARE
}
